### ISSUE TITLE
Sliding panel

### ISSUE THREAD

**Issue by SachaG** [superstringsoftware/observatory#1]
Sorry for hijacking the GitHub issues, but I didn't know how to reach you…

I've actually got two different sliding panels. The one to the right is just a couple lines of JS that change a CSS class on the body. 

The one on the left for the mobile version uses this plugin, although the implementation is currently buggy:

http://srobbin.com/jquery-plugins/pageslide/

And I'm also considering replacing it with this other plugin, which seems more solid but also a little more complex:

http://sidetap.it/

**Comment by jhoxray** [comment]
Thank you, will checkout overt the weekend!
