### ISSUE TITLE
Export logs

### ISSUE THREAD

**Issue by inhji** [superstringsoftware/observatory#2]
First of all, this is a great package, I stumbled across it this morning and immediately installed it.

But I have a feature request, as the title says, It would be nice to have the option to export all logs to a file and download it.

The format should be JSON, or a human readable format, as far as I'm concerned.

**Comment by jhoxray** [comment]
Agree, having an ability to analyze all logs is definitely needed. Was thinking about creating a separate "admin"-like page with advanced log manipulation (filtering, search, etc), but starting with a simple export sounds like a good idea.

**Comment by jhoxray** [comment]
Merged into #16
