### ISSUE TITLE
A way to disable HTTP logging

### ISSUE THREAD

**Issue by meawoppl** [superstringsoftware/observatory#22]
I am using observatory and leaflet together.  This results in a large number of http responses which clobber the logging I am trying to see.  Is there some way to disable this (I never even invoke a client side logging instance other than the display templates)

Thoughts/suggestions?

**Comment by ndhoule** [comment]
Under the usage section of the docs (https://github.com/jhoxray/observatory#usage), the method you're looking for is `.setOptions`. Passing `false` as the fourth argument disables http logging.

**Comment by meawoppl** [comment]
Much thanks sir!  Thanks for this awesome package.
