### ISSUE TITLE
Bootstrap dependency

### ISSUE THREAD

**Issue by iplanwebsites** [superstringsoftware/observatory#23]
I looked for a LONG time the evil package that forced a bootstrap dependency.
With the new version out (3.0), and many of us compiling the LESS version, it creates conflicts.

**Comment by jhoxray** [comment]
Very much welcome pull requests on this one.

**Comment by jhoxray** [comment]
Quick fix is making it a weak dependency, can do that.

**Comment by jhoxray** [comment]
Done.
