### ISSUE TITLE
Does not work with 0.6.5

### ISSUE THREAD

**Issue by meawoppl** [superstringsoftware/observatory#24]
Needs some symbols exported.  Perhaps in this package and apollo.  Werking on it here.

**Comment by meawoppl** [comment]
Alright, I have most of a pull-request composed.  There are several things that need attention.  
- The syntax for hooking in with connect changed
- The symbols TLog (and CodeMirror?) need to be exported in package.js

Can I rename the file "javascript.js" to something more descriptive codeMirrorJSHighlight.js or some such?

**Comment by jhoxray** [comment]
Hey, thanks - we were working on other projects and just got to updating Observatory to 0.6.5. If you figured out most of the issues would appreciate a pull request and yes, do rename the file. Otherwise we'll look into it the upcoming week.

**Comment by jhoxray** [comment]
Ok, updated to work with 0.6.5
