### ISSUE TITLE
Observatory CSS messes up main app

### ISSUE THREAD

**Issue by SachaG** [superstringsoftware/observatory#4]
I use some of the same class names and markup patterns as bootstrap in my app, although without using bootstrap itself. So Observatory wrecks a lot of things in the CSS.

**Comment by jhoxray** [comment]
Valid point but as I understand the only way over this is to restyle everything without Bootstrap, which is definitely possible but will take some time. Might as well add some style / theme-like configuration possibilities there as well.

**Comment by jhoxray** [comment]
PS Thanks for the logo :)

**Comment by SachaG** [comment]
No problem ;)

And I don't think you have to restyle anything, you just need to prefix all Boostrap styles with a ".observatory" class, that's all.
